### ISSUE TITLE
Can make report of Test and Score & Confusion Matrix automaticaly?

### ISSUE THREAD

**Issue by yuanxin-cq** [biolab/orange-scripts#5] opened 2022-01-12 05:44 UTC
When we do a loop data process in Orange3, report only can be saved one by one by hand.
Wish can make & save report  automaticaly, and it  would be great if  make report  in structure data and easily save into database  by python script widget.

![pic](https://user-images.githubusercontent.com/2495454/149070723-052387e5-5da9-4c8a-930e-dbc436ecb1fc.png)

**Comment by ajdapretnar** [comment] 2022-01-12 08:12
Closing this as a duplicate of https://github.com/biolab/orange3/issues/5777

**Closed by ajdapretnar** 2022-01-12 08:12 UTC
